[2023-04-02 18:06:52,796] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-02T18:06:51.021779+00:00 [queued]>
[2023-04-02 18:06:52,807] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-02T18:06:51.021779+00:00 [queued]>
[2023-04-02 18:06:52,808] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:06:52,809] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-02 18:06:52,809] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:06:52,824] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-02 18:06:51.021779+00:00
[2023-04-02 18:06:52,830] {standard_task_runner.py:52} INFO - Started process 619 to run task
[2023-04-02 18:06:52,835] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-04-02T18:06:51.021779+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvjvyjs8m', '--error-file', '/tmp/tmpsk7zmdzt']
[2023-04-02 18:06:52,837] {standard_task_runner.py:80} INFO - Job 6: Subtask is_api_available
[2023-04-02 18:06:52,904] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-04-02T18:06:51.021779+00:00 [running]> on host e18fbfc31089
[2023-04-02 18:06:52,981] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T18:06:51.021779+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T18:06:51.021779+00:00
[2023-04-02 18:06:52,983] {http.py:97} INFO - Poking: api/
[2023-04-02 18:06:52,994] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-04-02 18:06:52,997] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-02 18:06:53,237] {base.py:301} INFO - Success criteria met. Exiting.
[2023-04-02 18:06:53,250] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230402T180651, start_date=20230402T180652, end_date=20230402T180653
[2023-04-02 18:06:53,289] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-02 18:06:53,339] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
