[2023-04-02 18:06:57,179] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-04-02T18:06:51.021779+00:00 [queued]>
[2023-04-02 18:06:57,187] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-04-02T18:06:51.021779+00:00 [queued]>
[2023-04-02 18:06:57,189] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:06:57,189] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-02 18:06:57,190] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:06:57,203] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2023-04-02 18:06:51.021779+00:00
[2023-04-02 18:06:57,209] {standard_task_runner.py:52} INFO - Started process 628 to run task
[2023-04-02 18:06:57,213] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2023-04-02T18:06:51.021779+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmplh6py7vo', '--error-file', '/tmp/tmp92q3uaoy']
[2023-04-02 18:06:57,214] {standard_task_runner.py:80} INFO - Job 9: Subtask store_user
[2023-04-02 18:06:57,276] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user manual__2023-04-02T18:06:51.021779+00:00 [running]> on host e18fbfc31089
[2023-04-02 18:06:57,347] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T18:06:51.021779+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T18:06:51.021779+00:00
[2023-04-02 18:06:57,350] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-04-02 18:06:57,360] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-04-02 18:06:57,366] {python.py:173} INFO - Done. Returned value was: None
[2023-04-02 18:06:57,379] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20230402T180651, start_date=20230402T180657, end_date=20230402T180657
[2023-04-02 18:06:57,427] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-02 18:06:57,460] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
