[2023-04-02 18:06:55,991] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.process_user manual__2023-04-02T18:06:51.021779+00:00 [queued]>
[2023-04-02 18:06:56,000] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.process_user manual__2023-04-02T18:06:51.021779+00:00 [queued]>
[2023-04-02 18:06:56,001] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:06:56,002] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-02 18:06:56,002] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-02 18:06:56,016] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_user> on 2023-04-02 18:06:51.021779+00:00
[2023-04-02 18:06:56,022] {standard_task_runner.py:52} INFO - Started process 625 to run task
[2023-04-02 18:06:56,026] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'manual__2023-04-02T18:06:51.021779+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp48e83dfu', '--error-file', '/tmp/tmp_okc__lv']
[2023-04-02 18:06:56,027] {standard_task_runner.py:80} INFO - Job 8: Subtask process_user
[2023-04-02 18:06:56,087] {task_command.py:369} INFO - Running <TaskInstance: user_processing.process_user manual__2023-04-02T18:06:51.021779+00:00 [running]> on host e18fbfc31089
[2023-04-02 18:06:56,154] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T18:06:51.021779+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T18:06:51.021779+00:00
[2023-04-02 18:06:56,174] {python.py:173} INFO - Done. Returned value was: None
[2023-04-02 18:06:56,187] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=process_user, execution_date=20230402T180651, start_date=20230402T180655, end_date=20230402T180656
[2023-04-02 18:06:56,239] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-02 18:06:56,309] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
